### ISSUE TITLE
Darius missing as a champ on Top lane and API key is redundant

### ISSUE THREAD

**Issue by Feverfew** [solomidnet/championgg-api-python#4]
If you send a request to the API to this URL: http://api.champion.gg/stats/role/Top?page=1&limit=1000
First you'll notice that there is no API key in this request and I still get a response, meaning that people can send a request without the key, making having an API key at all, redundant.

Secondly, in this request I do not get any data on Darius at all even though he is played Top lane and he has data available on Top lane on the official champion.gg website. 
Could Darius be added ASAP to Top lane.

Thank you.

**Comment by Feverfew** [comment]
Bump.

Also the same applies to Vladimir, you cannot find him on Top Lane. At this point maybe it should be checked that all champions are found for each role as they are on the website as a few seem to be missing.

**Comment by Feverfew** [comment]
bump

**Comment by abaltra** [comment]
@Feverfew Thanks for the heads up. I'll look into it rn.

**Comment by abaltra** [comment]
@Feverfew I checked the data and the results from the API are consistent with what we have in the DB (even Kled's there!) Maybe you are missing some results because there's a hard cap of 50 elements per request. In the case of stats for top lane, there are 54 total results, so you'd need to make 2 calls to get all the data.

About the API token issue, we are aware of it, I'll leave this ticket open until that's resolved.

**Comment by Feverfew** [comment]
Thank you, yes the top lane issues were resolved. Please could I ask the hard limit to at least be taken up to 100 please? It makes it all the more insulting that the limit is only imposed on those with an api key as can be seen:
http://api.champion.gg/stats/role/Top?api_key=API_KEY?limit=1000
http://api.champion.gg/stats/role/Top?limit=1000

**Comment by abaltra** [comment]
@Feverfew You are getting that behaviour because you are separating the query parameters with `?` instead of `&`. 
http://api.champion.gg/stats/role/Top?api_key=API_KEY&limit=1000

Limits the data properly. We will look into the api keys not working though.

**Comment by pfugate** [comment]
@Feverfew The API_KEY is now working. Auth is back in place. Please use it in all your calls. I'll mark the issue as closed. 

The issue arose when we were having problems with our Redis cluster on AWS and we migrated the cluster to an external service. The LUA that sits on the front of the API to auth very quickly was not able to connect to our Redis right away (we had to resolve that too), so we just turned auth off, but its back on now.
