### ISSUE TITLE
limit cap to be raised to 100

### ISSUE THREAD

**Issue by Feverfew** [solomidnet/championgg-api-python#5]
For roles such as jungle/middle/top there are 53 champions but the cap is 50. Sending a whole request to get the last 3 is really tedious and creates unnecessary overhead. Could it please be increased to 100?:
http://api.champion.gg/stats/role/Jungle/mostImproved?api_key=API_KEY&limit=100

**Comment by abaltra** [comment]
Upper limit increased to 100. Closing the issue
